### ISSUE TITLE
DoS attack scenario starts with unintended S3 access

### ISSUE THREAD

**Issue by assaflavi** [aws-samples/aws-incident-response-runbooks#4]
Looks like [the intro to the DoS scenario](https://github.com/aws-samples/aws-incident-response-playbooks/blob/master/playbooks/IRP-DoS.md?plain=1#L42-L47) was copied from another playbook. Such an incident should probably be discovered some other way.

**Comment by phillisf** [comment]
Thanks for flagging this, @assaflavi . I will take a look.

**Comment by phillisf** [comment]
Corrected wording, corrected some grammatical errors in part 1. Resolving. Thanks for raising this, @assaflavi !
